### ISSUE TITLE
Проверка на undefined

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [IgorBelinskiy/React-Internship#10]
```
 src={photo === undefined
         ? userPhoto
         : photo} alt="userphoto" />
```
В данном случае можно опустить `undefined`,  тогда будет проверка что `photo` не равно `null`, `undefined`, 'false', а так же пустой строке, грубо говоря, в переменной будет какое-то значение
```
 src={photo ? photo : userPhoto} alt="userphoto" />
```

А в качестве значения по умолчанию можно переписать еще проще `photo ?? userPhoto` или `photo || userPhoto` они работаю немного по разному, нужно ориентироваться по ситуации

**Comment by IgorBelinskiy** [comment]
Переписал.
