### ISSUE TITLE
Использование ref не по назначению 

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [IgorBelinskiy/React-Internship#16]
https://ru.reactjs.org/docs/refs-and-the-dom.html
Использование рефов оправдано лишь в некоторых случаях, если можно не использовать рефы - значит нужно из не использовать.
В данном случаи ты используешь ref `draggingItem.current` как переменную. Но для переменных у нас есть `useState`
И твой код легко меняется на 
```
  const [draggingItem, setDraggingItem] = useState(null);

  const handleDragStart = (position) => {
    setDraggingItem(position);
  };
  const handleDragEnter = (position) => {
    const listCopy = [...dnd];
    const draggingItemContent = listCopy[draggingItem];
    listCopy.splice(draggingItem, 1);
    listCopy.splice(position, 0, draggingItemContent);

    setDraggingItem(position);
    setDnd(listCopy);
  };
```

**Comment by DmitriiMelnikOnix** [comment]
Тоже самое с `withDnd`

**Comment by IgorBelinskiy** [comment]
Согласен, без ref-ов намного лучше!
