### ISSUE TITLE
Переименование функций

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [IgorBelinskiy/React-Internship#2]
В подобной записи нет смыла
```
  const onDelLastItemBiography = () => {
      delLastItem();
   }
```
Лучше функцию `delLastItem` сразу назвать `onDelLastItemBiography`
Ну а если очень нужно будет переименовать, можно записать это проще (но лучше не нужно)
```
const onDelLastItemBiography = delLastItem;
```

**Comment by IgorBelinskiy** [comment]
Ok
